- components/cookies/index.js
- package.json
- yarn.lock
~~https://github.com/Vizzuality/gfw-components/pull/60 (1.8.4) must be published first.~~ - _It has been published_
This PR implements the new cookies design.  
https://gfw-blog-pr-66.herokuapp.com/blog/
[FLAG-484](https://gfw.atlassian.net/browse/FLAG-484)
> New cookies design

- layouts/layout/index.js
- pages/_document.js
This PR aims to fix the noindex robots metatag not working correctly.
> Fix local noindex robots metatag not overriding Yoast's one

- .gitignore
- pages/_document.js
adding Google Tag Manager script
> feat(document): add GTM script

- package.json
- yarn.lock
> FLAG-823: bump gfw-components 3.2.0

- layouts/layout/index.js
- package.json
- pages/[...slugs].js
- pages/index.js
- pages/search/[query].js
- pages/tag/[tag].js
- utils/notifications.js
- yarn.lock
> feat(notice-board): integrate notifications

- layouts/layout/index.js
- pages/404.js
- pages/_error.js
- pages/index.js
- pages/search/[query].js
- pages/tag/[tag].js
> fix(layout): import Layout on client side

- pages/[...slugs].js
> fix(layout): replace last occurence of ssr layout

- package.json
- yarn.lock
> bump GFW components to 3.5.0

- package.json
- pages/[...slugs].js
- yarn.lock
https://github.com/wri/gfw-blog/pull/96
> PROD Deploy 2023-11-14 2:19pm EST

- layouts/home/index.js
- package.json
- yarn.lock
> Implement Paginator in Home Page

- components/card/index.js
- components/card/styles.js
> Update Card styles

- components/header/index.js
- layouts/layout/index.js
- pages/404.js
- pages/[...slugs].js
- pages/_error.js
- pages/index.js
- pages/search/[query].js
- pages/tag/[tag].js
> bug(layout): create Header container to export client side

- components/card/index.js
- components/card/styles.js
> fix(featured-articles-styles): Update and fix padding

- components/card/index.js
- components/slider/index.js
- layouts/home/index.js
> feat(Card): Add showExcerpt prop to Card component

- components/card/index.js
- components/card/styles.js
- layouts/home/index.js
> FLAG-955: replace hardcoded reading time with actual value and update reading bar styles

- layouts/layout/index.js
> FLAG-977: remove twitter meta tags

- components/slider/styles.js
> chore(slider): hide scrollbar but keep its functionality

- layouts/home/index.js
- layouts/home/styles.js
> chore(home): address max-width styles

- components/results-list/styles.js
> FLAG-936 | chore: update language selector styles

- components/results-list/styles.js
- layouts/post/index.js
> chore: hide language selector if empty

- lib/api.js
- pages/[...slugs].js
> [FLAG-967] WP Redirection

- assets/icons/chevron-down-white.svg
- assets/icons/chevron-up-white.svg
- components/category-list/index.js
- components/category-list/styles.js
- components/search/index.js
- components/search/styles.js
- components/topics-list/index.js
- components/topics-list/styles.js
- layouts/archive/index.js
- layouts/home/index.js
- layouts/post/index.js
- pages/[...slugs].js
- pages/index.js
- pages/search/[query].js
- utils/constants.js
> FLAG-951: replace filtering options

- components/search/styles.js
- components/topics-list/styles.js
> FLAG-951: topics list grid styles

- components/explore-more/index.js
- components/explore-more/styles.js
- components/filter/index.js
- components/filter/styles.js
- components/not-find-what-youre-looking-for/index.js
- components/not-find-what-youre-looking-for/styles.js
- layouts/archive/index.js
- layouts/archive/styles.js
- layouts/search/index.js
- layouts/search/styles.js
- pages/search/[query].js
> [FLAG-1023] Duplicate Archive page to create a customized Search Page

- assets/icons/close-white.svg
- assets/icons/filter-arrow-up.svg
- components/category-list/index.js
- components/category-list/styles.js
- components/filter-dropdown/index.js
- components/filter-dropdown/styles.js
- components/filter/index.js
- components/filter/styles.js
- components/search/index.js
- components/search/styles.js
- components/topics-list/index.js
- components/topics-list/styles.js
- layouts/archive/index.js
- layouts/archive/styles.js
- layouts/search/index.js
- layouts/search/styles.js
- pages/tag/[tag].js
> FLAG-1024: pills and dropdown

- package.json
- yarn.lock
> Bump gfw components to 3.5.4

- components/topics-list/styles.js
> chore(topics): remove padding

- layouts/archive/index.js
- layouts/search/index.js
- pages/search/[query].js
> [FLAG-1025] Search Page Filter

- next.config.js
> fix(next.config.js): fetch diff pages

- package.json
- yarn.lock
> chore(package.json): bump gfw components 3.5.5

- components/category-list/styles.js
- layouts/home/index.js
- layouts/post/index.js
> More blog styles pt 1

- components/filter/styles.js
- layouts/post/index.js
- layouts/search/styles.js
addressing:
Please unbold the category / topic box text
please align the topics selected with the topics dropdown - they’re shifted to the right
The golden icon is above the white space when I scroll down
> more blog styles pt2

- next.config.js
> fix(next.config.js): add per_page param

- next.config.js
https://github.com/wri/gfw-blog/pull/148
> PROD Deploy 2024-03-06 09:25pm EST

- layouts/post/meta/index.js
> chore(article): remove topic limit display

- components/content/styles.js
Swapping h2 and h3 styles which were incorrect.
> FLAG-1072: swap h2 and h3 styles

- components/content/styles.js
- layouts/post/meta/index.js
https://github.com/wri/gfw-blog/pull/153
> PROD Deploy 2024-04-03 02:03pm EST

- layouts/post/styles.js
Downsizing title and image in articles page.
-
-
-
> FLAG-1087: downsize title and image

- components/filter-dropdown/styles.js
> [FLAG-1085] Move filtering options closer together, reduce size of categories dropdown

- package.json
- yarn.lock
> FLAG-1097 - replace terms of service url

- components/filter-dropdown/styles.js
- package.json
- yarn.lock
https://github.com/wri/gfw-blog/pull/168
> PROD Deploy 2024-05-07 02:52pm EST

- components/card/index.js
> [FLAG-1084] Make home page thumbnails match other pages' thumbnails

- components/content/styles.js
> [FLAG-1089] Align article body and graphics

- components/search/styles.js
- components/topics-list/styles.js
> [FLAG-1082] Ensure that wrapping doesn’t hide topic text

- components/filter/styles.js
- layouts/post/share-links/styles.js
> FLAG-1088: align buttons with content

- components/card/index.js
- hooks/use-get-tx-locale.js
- hooks/use-localize-yoast-reading-time.js
- layouts/post/index.js
Accounting for overriding value for Estimate Reading Time
-
-
-
> FLAG-1081: account for manual reading time override value

- components/back-button/styles.js
- layouts/post/index.js
- layouts/post/styles.js
> chore(sticky-back-button): transform back button into sticky element

- layouts/layout/index.js
- package.json
- pages/_document.js
- yarn.lock
> FLAG-1037: add osano drawer call

- redirects.json
https://github.com/wri/gfw-blog/pull/197
> PROD Deploy 2025-06-11 05:41pm EST

- layouts/post/meta/index.js
- redirects.json
https://github.com/wri/gfw-blog/pull/199
> PROD Deploy 2025-06-23 10:22am EST
